/**
 * Class for static constants used for Test classes ONLY
 *
 * <p></p>
 *
 * @author Maryem BOURHI(mbourhi @salesforce.com)
 *
 * @date Nov 24th 2020
 */
public with sharing class AOB_TestConstants {
  public static final String TOKEN='eyJhbGciOiJSUzI1NiIsImtpZCI6ImRpZC0xIiwicGkuYXRtIjoiOGlraSJ9.eyJzY3AiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIl0sImNsaWVudF9pZCI6IjI3MzEwZjFlLTBlZGEtNDM1MS05OTYxLTUwMTQ2NDFjYzBmNSIsImlzcyI6Imh0dHBzOi8vZW50ZXJwcmlzZXN0c3NpdC5zdGFuZGFyZGJhbmsuY28uemEiLCJqdGkiOiJlWHZrbzVoa3dKcHNGVjRGYTE2TkRJIiwic3ViIjoiZmlyc3R0d29AZ21haWwuY29tIiwiZGlnaW1lIjoiRmFsc2UiLCJuYmYiOjE2MTc2MzIxMDQsImJwaWQiOiIwNTMzMzIyODE5IiwiYnBpZGd1aWQiOiJBRUE4RjQxRjAwMDYxRURCOTA4Nzk5MjMyQzNBQTEzMiIsImlkIjoiMDViZDQzMGEtMzhmYi00NjhjLThjZDUtZThiMWJiYWE5ZWY1IiwiaWF0IjoxNjE3NjMyMTA0LCJleHAiOjE2MTc2MzI0MDR9.ZkLpH6OYZf_u9K-wNu87z-5D07dX8nQYYkxLm_cv-N_MI0kqakgXDfvWLjVYWZ5yKDVkAKMd-cJgzgZII55Kw79w_S-4rrbTc6qUQMjx9mdZAPCIbjV_jOKxWcbHmzh6kkK3NajONaUMRHOIrk1wGSl-B_0_cAyOelEeppu6XH78MmfqaC9yR01cRIZdyjvFJ3fypyU43A4eYGT8TkrhKegCN6uOFZmO_FktjPFXbsjH-KOJY8mZaO2v9JC-T3giiud9JgUNE9KE8FpT5cOg1cHuLjkvgZxD3gqZ6vbQw-YF2Z5vOjPC0yR2ekxMg4D-MzpKOoH90vPH0YS1Ubdcxw';
  public static final Integer CURRENT_SCREEN_NUMBER = 3;
  public static final Integer NUMBER_OF_SCREENS = 5;
  public static final String CURRENT_SCREEN = 'Current Screen';
  public static final String PREVIOUS_SCREEN = 'Previous Screen';
  public static final String PRODUCT_NAME = 'WORLD CITIZEN CREDIT CARD';
  public static final String REQUIRED_DOC_DESCRIPTION = 'Required Document Description';
  public static final String REQUIRED_DOC_HELPTEXT = 'Required Document Help Text';
  public static final Integer REQUIRED_DOC_ORDER = 1;
  public static final String PRODUCT_QUALIF_DESCRIPTION = 'Product Qualification Description';
  public static final String PRODUCT_QUALIF_HELPTEXT = 'Product Qualification Help Text';
  public static final Integer PRODUCT_QUALIF_ORDER = 1;
  public static final String SERVICE_NAME = 'Service Name';
  public static final String RESPONSE = 'Response';
  public static final String SYSTEM_ADMINISTRATOR = 'System Administrator';
}