/**
 * Domain class for Log_c SObject
 * <br/> US-4824
 *
 * @author Wojciech Kowalczyk (wkowalczyk@deloittece.com)
 * @date June 2020
 */
public without sharing class DMN_Log {

	public static final String AREA_COMMB = 'Digisign_CommB';
	public static final String AREA_AOB = 'Account Onboarding';
	public static final String AREA_ONEHUB = 'OneHub';
    public static final String AREA_PARTNERPORTAL = 'PartnerPortal';
	public static final String AREA_IB_DCP = 'IB_DCP';
	public static final String AREA_PBB_GATEWAY = 'PBB Gateway API integration';
	public static final String AREA_PBB_PARTNER_SYNC = 'Partner Sync Merge Integration';
	public static final String AREA_SERVICECLOUD = 'ServiceCloud';
	public static final String TYPE_ERROR = 'ERROR';
	public static final String TYPE_INFO = 'INFO';
	public static final String AREA_RELATEDPARTY = 'RelatedParty';
	private static final String LOGS_DASHBOARD_NAME = 'eXlNPfbmiigbhJdQzHLzXRNQZvsQNd';

}